<?php

namespace app\index\controller;
use app\common\controller\Frontend;
use app\admin\model;

/**
 * 默认控制器
 * @author Sir Fu
 */
class Contact extends Frontend
{
    //广告类别
    private $sliderType = 7;
private $model=null;
private $modelUser=null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model=model("Company");
        $this->modelUser=model("Admin");
        $this->assign('nav','contact');
    }

    /**
     * 默认方法
     * @author Sir Fu
     */
    public function index()
    {

        $company = $this->model->find();
        $this->view->assign("row",$company);
        return $this->fetch();
    }
    public function zhiyeguwen()
    {
        if ($this->request->isAjax()) {
            list($where, $sort, $order, $offset, $limit) = $this->buildparams(NULL);
            //var_dump($where);die();
            //$where['HouseType']=['=',1];
            $total = $this->modelUser
                ->where(['GoldConsultant_switch'=>1])
                ->where($where)
                ->order($sort, $order)
                ->count();
            $list = $this->modelUser
                ->where(['GoldConsultant_switch'=>1])
                ->where($where)
                ->order($sort, $order)
                ->limit($offset, $limit)
                ->select();
            $result = array("total" => $total, "rows" => $list);

            return json($result);
        }
    }
    /**
     * 显示创建资源表单页.| 保存新建的资源
     *
     * @return \think\Response
     */
    public function createAction()
    {
        $ret = ['status'=>'0','info'=>'提交失败'];
        if ($this->getRequest()->isPost()){
            $model = new Contact();
            $data = $model->filter($_POST);
            if ($data){
                $data['home_user_id'] = $this->getIdentity('id')?:'0';
                $data['back_user_id'] = isset($data['back_user_id'])? $data['back_user_id'] :'0';
                $data['created_at'] = date('Y-m-d H:i:s');
                $validate = Contact::getValidate();
                $validate->scene('create');
                if ($validate->check($data) && $model->save($data)){
                    $ret = ['status'=>'1','info'=>'提交成功'];
                }else{
                    $error = $validate->getError();
                    if (empty($error)){
                        $error = $model->getError();
                    }
                    $ret = ['status'=>'0','info'=>$error];
                }
            }
        }
        return json($ret);
    }


}
